# Generated by Django 3.2.9 on 2021-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corporate', '0002_templates_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare_Management_Emplyee_Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(null=True)),
                ('route', models.CharField(max_length=80, null=True)),
                ('model', models.CharField(max_length=80, null=True)),
                ('fuel_type', models.CharField(max_length=80, null=True)),
                ('window_fare', models.FloatField(null=True)),
                ('middle_seat_fare', models.FloatField(null=True)),
                ('gst', models.FloatField(null=True)),
                ('insurance', models.FloatField(null=True)),
                ('fare_per_seat_window', models.IntegerField(null=True)),
                ('middle_seat', models.IntegerField(null=True)),
                ('option', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Management_Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(null=True)),
                ('route', models.CharField(max_length=80, null=True)),
                ('model', models.CharField(max_length=80, null=True)),
                ('fuel_type', models.CharField(max_length=80, null=True)),
                ('window_fare', models.FloatField(null=True)),
                ('middle_seat_fare', models.FloatField(null=True)),
                ('gst', models.FloatField(null=True)),
                ('insurance', models.FloatField(null=True)),
                ('fare_per_seat_window', models.IntegerField(null=True)),
                ('middle_seat', models.IntegerField(null=True)),
                ('option', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Management_Outstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(null=True)),
                ('route', models.CharField(max_length=80, null=True)),
                ('model', models.CharField(max_length=80, null=True)),
                ('fuel_type', models.CharField(max_length=80, null=True)),
                ('window_fare', models.FloatField(null=True)),
                ('middle_seat_fare', models.FloatField(null=True)),
                ('gst', models.FloatField(null=True)),
                ('insurance', models.FloatField(null=True)),
                ('fare_per_seat_window', models.IntegerField(null=True)),
                ('middle_seat', models.IntegerField(null=True)),
                ('option', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Fare_Management',
            new_name='Fare_Management_Employee_Transportation',
        ),
        migrations.AddField(
            model_name='listing_assign_management',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
