# Generated by Django 3.2.9 on 2021-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cab_Service', '0002_rename_fuel_mangement_fuel_management_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance_management',
            old_name='vehicle_no',
            new_name='_no',
        ),
    ]
