# Generated by Django 3.2.9 on 2021-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Templates_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('booking_confirmation_sms', models.CharField(max_length=80)),
                ('for_verification_otp_sms', models.CharField(max_length=80)),
                ('resetpassword_otp', models.CharField(max_length=80)),
                ('booking_cancel_sms', models.CharField(max_length=80)),
                ('email_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_Monitering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vehicle', models.IntegerField()),
                ('running_vehicle', models.IntegerField()),
                ('breakdown_vehicle', models.IntegerField()),
                ('maintaince_vehicle', models.IntegerField()),
                ('vehicle_number', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('view', models.ImageField(null=True, upload_to='')),
                ('Co_Partner_Access', models.CharField(max_length=80)),
                ('map_view', models.ImageField(upload_to='media')),
            ],
        ),
    ]
