# Generated by Django 3.2.9 on 2021-12-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('booking_confirmation_sms', models.CharField(max_length=80)),
                ('for_verification_otp_sms', models.CharField(max_length=80)),
                ('resetpassword_otp', models.CharField(max_length=80)),
                ('booking_cancel_sms', models.CharField(max_length=80)),
                ('email_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
